const Users = {
  users: [
    {
      name: "Joseph",
      age: 30,
      city: "New Delhi",
      email_address: "joseph@gmail.com",
    },
    {
      name: "Alice",
      age: 28,
      city: "Mumbai",
      email_address: "alice@gmail.com",
    },
    {
      name: "Bob",
      age: 35,
      city: "Bangalore",
      email_address: "bob@gmail.com",
    },
    {
      name: "Carol",
      age: 32,
      city: "Chennai",
      email_address: "carol@gmail.com",
    },
    {
      name: "David",
      age: 40,
      city: "Hyderabad",
      email_address: "david@gmail.com",
    },
    {
      name: "Eva",
      age: 25,
      city: "Pune",
      email_address: "eva@gmail.com",
    },
    {
      name: "Frank",
      age: 45,
      city: "Kolkata",
      email_address: "frank@gmail.com",
    },
    {
      name: "Grace",
      age: 29,
      city: "Ahmedabad",
      email_address: "grace@gmail.com",
    },
    {
      name: "Hank",
      age: 38,
      city: "Surat",
      email_address: "hank@gmail.com",
    },
    {
      name: "Ivy",
      age: 27,
      city: "Jaipur",
      email_address: "ivy@gmail.com",
    },
    {
      name: "Jack",
      age: 34,
      city: "Vadodara",
      email_address: "jack@gmail.com",
    },
    {
      name: "Karen",
      age: 31,
      city: "Visakhapatnam",
      email_address: "karen@gmail.com",
    },
    {
      name: "Leo",
      age: 26,
      city: "Bhubaneswar",
      email_address: "leo@gmail.com",
    },
    {
      name: "Mia",
      age: 33,
      city: "Guwahati",
      email_address: "mia@gmail.com",
    },
    {
      name: "Nate",
      age: 39,
      city: "Chandigarh",
      email_address: "nate@gmail.com",
    },
    {
      name: "Olivia",
      age: 24,
      city: "Indore",
      email_address: "olivia@gmail.com",
    },
    {
      name: "Paul",
      age: 37,
      city: "Coimbatore",
      email_address: "paul@gmail.com",
    },
    {
      name: "Quinn",
      age: 26,
      city: "Mysore",
      email_address: "quinn@gmail.com",
    },
    {
      name: "Rita",
      age: 30,
      city: "Tiruchirappalli",
      email_address: "rita@gmail.com",
    },
    {
      name: "Sam",
      age: 29,
      city: "Nagpur",
      email_address: "sam@gmail.com",
    },
    {
      name: "Tina",
      age: 28,
      city: "Agra",
      email_address: "tina@gmail.com",
    },
    {
      name: "Ursula",
      age: 32,
      city: "Jalandhar",
      email_address: "ursula@gmail.com",
    },
    {
      name: "Victor",
      age: 35,
      city: "Dehradun",
      email_address: "victor@gmail.com",
    },
    {
      name: "Wendy",
      age: 41,
      city: "Ranchi",
      email_address: "wendy@gmail.com",
    },
    {
      name: "Xander",
      age: 27,
      city: "Shimla",
      email_address: "xander@gmail.com",
    },
    {
      name: "Yara",
      age: 34,
      city: "Srinagar",
      email_address: "yara@gmail.com",
    },
    {
      name: "Zane",
      age: 26,
      city: "Udaipur",
      email_address: "zane@gmail.com",
    },
    {
      name: "Anna",
      age: 30,
      city: "Trivandrum",
      email_address: "anna@gmail.com",
    },
    {
      name: "Ben",
      age: 29,
      city: "Kochi",
      email_address: "ben@gmail.com",
    },
    {
      name: "Clara",
      age: 33,
      city: "Kolkata",
      email_address: "clara@gmail.com",
    },
    {
      name: "Derek",
      age: 40,
      city: "Lucknow",
      email_address: "derek@gmail.com",
    },
    {
      name: "Ella",
      age: 27,
      city: "Gwalior",
      email_address: "ella@gmail.com",
    },
    {
      name: "Fred",
      age: 36,
      city: "Rajkot",
      email_address: "fred@gmail.com",
    },
    {
      name: "Gina",
      age: 31,
      city: "Jamshedpur",
      email_address: "gina@gmail.com",
    },
    {
      name: "Harry",
      age: 29,
      city: "Pondicherry",
      email_address: "harry@gmail.com",
    },
    {
      name: "Irene",
      age: 32,
      city: "Durgapur",
      email_address: "irene@gmail.com",
    },
    {
      name: "John",
      age: 28,
      city: "Aurangabad",
      email_address: "john@gmail.com",
    },
    {
      name: "Kate",
      age: 34,
      city: "Patna",
      email_address: "kate@gmail.com",
    },
    {
      name: "Leo",
      age: 35,
      city: "Amritsar",
      email_address: "leo2@gmail.com",
    },
    {
      name: "Lily",
      age: 26,
      city: "Bilaspur",
      email_address: "lily@gmail.com",
    },
    {
      name: "Mark",
      age: 31,
      city: "Mangalore",
      email_address: "mark@gmail.com",
    },
    {
      name: "Nina",
      age: 29,
      city: "Vadodara",
      email_address: "nina@gmail.com",
    },
    {
      name: "Omar",
      age: 33,
      city: "Shimla",
      email_address: "omar@gmail.com",
    },
    {
      name: "Pauline",
      age: 28,
      city: "Jodhpur",
      email_address: "pauline@gmail.com",
    },
    {
      name: "Quincy",
      age: 37,
      city: "Meerut",
      email_address: "quincy@gmail.com",
    },
  ],
};
